### ISSUE TITLE
How-to fetch server dependencies missing from README

### ISSUE THREAD

**Issue by platisd** [platisd/indoor-navigation-system#1]
As a newcomer developer I want a command-level instructions on how to set up the server dependencies so to be able to effortlessly set it up.

DoD:
* The commands and other instructions on how to fetch the dependencies that will enable developers to build the server and set-up the environment are present on the README.

**Comment by samup4web** [comment]
I will be working on a detailed instructions on setting up the dependencies asap.

**Comment by platisd** [comment]
You actually don't have to. :smiley: In theory this could be taken up by anyone but when you are to start it, then assign it to yourself and move it to the "In Progress" column of the board! :+1:
