### ISSUE TITLE
Missing test infrastructure - ins-node

### ISSUE THREAD

**Issue by platisd** [platisd/indoor-navigation-system#16]
As a CI machine I would like to be able to have the infrastructure in place which will enable me to run unit tests.

DoD:
* `build_and_run_ut.sh` script inside `ins-node` directory which builds and runs a sample unit test.

Protip:
* Follow [smartcar-gmock](https://github.com/platisd/smartcar-gmock) structure for testing and mocking arduino.

**Comment by samup4web** [comment]
So, after preparing my commit for test infrastructure for the server. I saw [this](https://github.com/platisd/indoor-navigation-system/blob/323b52b1a12611e5bdb707e32dee58535e1602ca/ins-node/test/arduino_mock/CMakeLists.txt#L5-L9) in your commit. That is super new to me. I guess I wouldn't need a copy of gtest/gmock with your approach. I will fix the feature branch before making a pull request. Cheers!

**Comment by platisd** [comment]
You don't really *have* to follow that approach, but if you think it makes sense sure, go for it! :+1:  :smiley:

**Comment by samup4web** [comment]
Yeah, I think it's a cool approach 😄
