### ISSUE TITLE
Missing hardware prototype

### ISSUE THREAD

**Issue by platisd** [platisd/indoor-navigation-system#19]
As an INS-node I want become materialized so to stop being a figment of imagination and speculation.

DoD:
* Board layout and schematics designed in [Eagle CAD](https://www.autodesk.com/products/eagle/overview)
* ~~[Fritzing](http://fritzing.org/home/) diagram added in [README.md](https://github.com/platisd/indoor-navigation-system/blob/master/ins-node/README.md)~~

**Comment by platisd** [comment]
@samup4web @lexious89 I was thinking about the optimum hardware setup for the beginning and concluded on a [Wemos D1 Mini](https://wiki.wemos.cc/products:d1:d1_mini), **instead** of an [ESP-01](https://4tronix.co.uk/store/resources/image/18/c2/2.jpg), Attiny25 (or 85) combo. This means that the total architecture will change a little bit as to where the main business logic is contained.

According to the old setup:
* ESP-01 was operated in AT-mode, meaning that we send commands to it via UART.
* Attiny parses the results and handles power management.

According to the new setup:
* We program the ESP8266 on the Wemos D1 Mini directly.
* Attiny handles power management.

Advantages :vs: disadvantages of the new approach:
* Easier and faster to develop/modify the main business logic since the Wemos can be programmed over USB with the Arduino IDE. :white_check_mark:
* For development we can practically use any other ESP8266 USB development module like the one @lexious89 has. :white_check_mark:
* Slightly more expensive. (ESP-01 costs ~1.6$ while Wemos D1 Mini costs ~2.6$) :x: 
* Slightly larger. :x: 
* Faster and more versatile setup since we do not rely on already made AT-commands to access the ESP8266 but we program it directly. :white_check_mark:
* Simpler and fewer hardware connections on the PCB from our side, meaning less risk. :white_check_mark:

Does it sound good? :smiley: 

PS. Also thinking of a knowledge sharing workshop on PCB design where I can go over how to design the board if you are interested in it!

**Comment by samup4web** [comment]
Sounds like a good idea. I guess the cost impact is quite marginal, and for the size, as long as we can package it in something nice then I see no problem. 

The PCB design knowledge sharing is a great idea!.

**Comment by platisd** [comment]
I have scratched out the creation of a Fritzing diagram as it will be redundant work at this point.
