### ISSUE TITLE
Backend Impl - REST Server

### ISSUE THREAD

**Issue by platisd** [platisd/indoor-navigation-system#4]
As a developer, I would like to have REST server that can handle HTTP POST/GET requests, so that devices & frontend app can communicate with the server.

**Comment by platisd** [comment]
Is this done @samup4web ?

**Comment by samup4web** [comment]
This issue and the database impl issue are somehow in the same boat. More work to be done as new related tasks unfolds.

**Comment by samup4web** [comment]
Fixed in [commit](https://github.com/platisd/indoor-navigation-system/commit/8e1333d574c81e35b327888606187d7dc6828c4e)
