### ISSUE TITLE
Backend Impl - Database

### ISSUE THREAD

**Issue by platisd** [platisd/indoor-navigation-system#5]
As a developer, I would like to have a database that can be used by the developed application.

**Comment by platisd** [comment]
Is this done @samup4web ?

**Comment by samup4web** [comment]
@platisd a part of this is done and there are more database related tasks that will still come up. I can have this  assigned to me since I already began with some part of this. 

Edit: Haha, just saw that you already assigned to me. Missed that earlier :)

**Comment by samup4web** [comment]
Fixed in [commit](https://github.com/platisd/indoor-navigation-system/commit/8e1333d574c81e35b327888606187d7dc6828c4e)
