### ISSUE TITLE
Add commit template

### ISSUE THREAD

**Issue by samup4web** [platisd/indoor-navigation-system#54]
As a developer I would like to have a commit template to facilitate [good commit messages](https://chris.beams.io/posts/git-commit/)

DoD
 * Script to configure git commit template according to project standard.

**Comment by platisd** [comment]
Do you have an example where this is used?

**Comment by samup4web** [comment]
A quick search - https://git-template.readthedocs.io/en/latest/

**Comment by platisd** [comment]
Hmmm, I still did not understand how will it help us. Will it run some checks over the commit contents (e.g. clang format) and not allow you to commit until you satisfy those checks?

**Comment by samup4web** [comment]
Basically it makes it easier to follow a uniform commit message format for all contributors/commits. When you run `git commit`, you will be presented with a specified template such as the one below

`#Title: here goes nice good short title, gives highlight of what changes are >`
  
  `#Details : <More details on why for need of changes>`
  `#Issue no : <if it issue no. , an issue raised if any>`

Of course this can take any format we desire in the project.

**Comment by platisd** [comment]
Aha I see. Yes, we could have it like that, but maybe with comments instead (i.e. `#` added in front of every line) so a committer won't have to delete text every time.
