### ISSUE TITLE
Missing dependency to spdlog

### ISSUE THREAD

**Issue by platisd** [platisd/indoor-navigation-system#57]
## Description
Our current `server/build.sh` script does not build the `server` correctly unless `spdlog` is already installed in the system, which beats the purpose of including `spdlog` in our `server/include/external` directory. This slipped through as Travis does not build the server itself but just the tests.

## Definition of Done
* Fix the dependency error
* Have Travis build the server

**Comment by platisd** [comment]
Originally reported by @lexious89

**Comment by lexious89** [comment]
Okey! But I thought @samup4web commented out all references to spdlog.

**Comment by platisd** [comment]
Hmmm, not sure what you mean. There was indeed a problem. Have a look at #58 for the fix.

**Comment by samup4web** [comment]
@lexious89 I am not sure I understand you either. But, what I have done removing the dependency to `spdlog` was  basically adding the source file to this project, and somehow introduced this issue which you experienced earlier.
