### ISSUE TITLE
Missing contribution guidelines

### ISSUE THREAD

**Issue by platisd** [platisd/indoor-navigation-system#6]
As an open source developer I would like to know the guidelines according to which my contributions should comply so I can co-exist within the community more seamlessly.

DoD:
* First draft of CONTRIBUTING.md is created.

**Comment by platisd** [comment]
A good example can be found [here](https://gist.github.com/PurpleBooth/b24679402957c63ec426).

**Comment by samup4web** [comment]
Issue closed under a duplicate #47

**Comment by platisd** [comment]
Marked as duplicate
