### ISSUE TITLE
Frontend Android App

### ISSUE THREAD

**Issue by samup4web** [platisd/indoor-navigation-system#8]
As a user, I can lookup employee location from my mobile phone so that I can determine their location.

Scope: 
* A basic Android app with an input field for employee id and a submit button.
* App sends HTTP GET request to server
* App displays position data in the form `(x,y)`

**Comment by platisd** [comment]
I would disagree that this is a single story/issue (it's too big!) and also due to be delivered on the first customer meeting! 😄 Let's talk about it today.

**Comment by samup4web** [comment]
I somehow agree with you, I guess I was feeling over optimistic here, or perhaps was thinking of a basic solution that can be later improved for this and #9  :smile: OK we will talk about this when we meet.

**Comment by samup4web** [comment]
This is no longer relevant, and can be closed.

**Comment by platisd** [comment]
Duplicated by #73
